// ============================================================
// geminiReasoning.service.js
// NexaSense AI Assistant
// Post-processing reasoning layer using Gemini
// Improves RAG answers with clearer explanation
// Production optimized
// ============================================================

const { askGemini } = require("./gemini.service");
const logger = require("../utils/logger");

const MAX_SOURCE_PREVIEW = 120;
const MAX_REASONING_TIME = 30000; // ms safety timeout

// ------------------------------------------------------------
// Build evidence context from retrieved sources
// ------------------------------------------------------------
function buildEvidence(sources = []) {

  if (!sources || !sources.length) return "";

  try {

    return sources
      .slice(0,5) // limit context
      .map(s => {

        const page =
          s.pageNumber
            ? `Page ${s.pageNumber}`
            : "";

        const preview =
          (s.preview || "")
            .replace(/\s+/g," ")
            .slice(0,MAX_SOURCE_PREVIEW);

        return `${page}: ${preview}`;

      })
      .join("\n");

  }

  catch {

    return "";

  }

}


// ------------------------------------------------------------
// Safe Gemini call with timeout
// ------------------------------------------------------------
async function callGeminiWithTimeout(prompt) {
  
  try {
    return await Promise.race([
      askGemini(prompt),
      new Promise((_, reject) =>
        setTimeout(() =>
          reject(new Error("Gemini reasoning timeout")),
          MAX_REASONING_TIME
        )
      )
    ]);
  } catch (error) {
    logger.warn("[GeminiReasoning] call failed/timed out:", error.message);
    return null;
  }

}


// ------------------------------------------------------------
// Apply reasoning to improve RAG answer
// ------------------------------------------------------------
async function applyReasoning(question, ragAnswer, sources = []) {

  try {

    if (!ragAnswer || typeof ragAnswer !== "string") {
      return ragAnswer;
    }

    // prevent unnecessary reasoning on short answers
    if (ragAnswer.length < 40) {
      return ragAnswer;
    }

    const evidence = buildEvidence(sources);

    const prompt = `
You are an expert AI Reasoning Engine. Your task is to refine and elevate an answer generated by a primary RAG (Retrieval-Augmented Generation) system.

Your goal is to maximize clarity, logic, formatting, and readability, WITHOUT hallucinating or introducing any external knowledge outside the provided evidence.

User Question:
${question}

Original Answer (from primary LLM):
${ragAnswer}

Document Evidence (Context):
${evidence}

## Refinement Rules:
1. **Elevate the prose:** Make the tone highly professional, precise, and articulate.
2. **Improve Formatting:** Ensure the response uses excellent Markdown. Add bolding to key concepts, use bullet points for lists, and use short paragraphs for readability.
3. **Fact-Check:** Ensure the Original Answer does not contradict the Document Evidence. If it does, correct it based ONLY on the Document Evidence.
4. **Preserve Fallback Warnings:** If the Original Answer starts with a warning like "⚠️", you MUST preserve that warning exactly as it is at the very top.
5. **No Fluff:** Do not repeat the user's question. Do not add introductory filler like "Here is the improved answer:".
6. **Output ONLY the final, polished Markdown answer.**
`;

    const improved = await callGeminiWithTimeout(prompt);

    if (!improved || improved.trim().length < 10) {
      return ragAnswer;
    }

    return improved.trim();

  }

  catch (error) {

    logger.warn("[GeminiReasoning] skipped:", error.message);

    // fallback to original RAG answer
    return ragAnswer;

  }

}


module.exports = {
  applyReasoning
};