// ============================================================
// geminiReasoning.service.js
// NexaSense AI Assistant
// Post-processing reasoning layer using Gemini
// Improves RAG answers with clearer explanation
// Production optimized
// ============================================================

const { askGemini } = require("./gemini.service");
const logger = require("../utils/logger");

const MAX_SOURCE_PREVIEW = 120;
const MAX_REASONING_TIME =30000; // ms safety timeout

// ------------------------------------------------------------
// Build evidence context from retrieved sources
// ------------------------------------------------------------
function buildEvidence(sources = []) {

  if (!sources || !sources.length) return "";

  try {

    return sources
      .slice(0,5) // limit context
      .map(s => {

        const page =
          s.pageNumber
            ? `Page ${s.pageNumber}`
            : "";

        const preview =
          (s.preview || "")
            .replace(/\s+/g," ")
            .slice(0,MAX_SOURCE_PREVIEW);

        return `${page}: ${preview}`;

      })
      .join("\n");

  }

  catch {

    return "";

  }

}


// ------------------------------------------------------------
// Safe Gemini call with timeout
// ------------------------------------------------------------
async function callGeminiWithTimeout(prompt) {
  
  try {
    return await Promise.race([
      askGemini(prompt),
      new Promise((_, reject) =>
        setTimeout(() =>
          reject(new Error("Gemini reasoning timeout")),
          MAX_REASONING_TIME
        )
      )
    ]);
  } catch (error) {
    logger.warn("[GeminiReasoning] call failed/timed out:", error.message);
    return null;
  }

}


// ------------------------------------------------------------
// Apply reasoning to improve RAG answer
// ------------------------------------------------------------
async function applyReasoning(question, ragAnswer, sources = []) {

  try {

    if (!ragAnswer || typeof ragAnswer !== "string") {
      return ragAnswer;
    }

    // prevent unnecessary reasoning on short answers
    if (ragAnswer.length < 40) {
      return ragAnswer;
    }

    const evidence = buildEvidence(sources);

    const prompt = `
You are refining an answer generated by a document retrieval system.

Your job is to improve clarity and structure WITHOUT introducing any
new knowledge outside the provided information.

User Question:
${question}

Original Answer:
${ragAnswer}

Document Evidence:
${evidence}

Rules:
• Do NOT add external knowledge
• Keep answer grounded in document evidence
• Improve readability and explanation
• Use bullet points if useful
• If answer is already good, return a slightly improved version
• Do NOT repeat the question

Return only the improved answer.
`;

    const improved = await callGeminiWithTimeout(prompt);

    if (!improved || improved.trim().length < 10) {
      return ragAnswer;
    }

    return improved.trim();

  }

  catch (error) {

    logger.warn("[GeminiReasoning] skipped:", error.message);

    // fallback to original RAG answer
    return ragAnswer;

  }

}


module.exports = {
  applyReasoning
};