// ============================================================
// geminiReasoning.service.js
// NexaSense AI Assistant
// Production-Grade Reasoning Layer (Safe + Controlled)
// ============================================================

const { askGemini } = require("./gemini.service");
const logger = require("../utils/logger");

const MAX_SOURCE_PREVIEW = 120;
const MAX_REASONING_TIME = 30000; // timeout safety


// ------------------------------------------------------------
// Build evidence context from retrieved sources
// ------------------------------------------------------------
function buildEvidence(sources = []) {

  if (!sources || !sources.length) return "";

  try {

    return sources
      .slice(0, 5) // limit evidence
      .map(s => {

        const page =
          s.pageNumber
            ? `Page ${s.pageNumber}`
            : "";

        const preview =
          (s.preview || "")
            .replace(/\s+/g, " ")
            .slice(0, MAX_SOURCE_PREVIEW);

        return `${page}: ${preview}`;

      })
      .join("\n");

  } catch {
    return "";
  }

}


// ------------------------------------------------------------
// Safe Gemini call with timeout
// ------------------------------------------------------------
async function callGeminiWithTimeout(prompt) {

  try {

    return await Promise.race([
      askGemini(prompt),
      new Promise((_, reject) =>
        setTimeout(() =>
          reject(new Error("Gemini reasoning timeout")),
          MAX_REASONING_TIME
        )
      )
    ]);

  } catch (error) {

    logger.warn("[GeminiReasoning] timeout/failure:", error.message);
    return null;

  }

}


// ------------------------------------------------------------
// Apply reasoning (safe refinement only)
// ------------------------------------------------------------
async function applyReasoning(question, ragAnswer, sources = []) {

  try {

    // basic validation
    if (!ragAnswer || typeof ragAnswer !== "string") {
      return ragAnswer;
    }

    // skip very short answers (no need to refine)
    if (ragAnswer.length < 40) {
      return ragAnswer;
    }

    const evidence = buildEvidence(sources);

    const prompt = `
You are an expert AI Reasoning Engine.

Your task is to refine and improve an answer generated by a primary RAG system.

⚠️ CRITICAL: You must NOT introduce any new facts.

---

User Question:
${question}

Original Answer:
${ragAnswer}

Document Evidence:
${evidence}

---

## STRICT GROUNDING

- You MUST NOT add new information
- You MUST NOT assume missing details
- You MUST NOT expand beyond given content
- You are ONLY allowed to:
  • rephrase
  • restructure
  • clarify

---

## EVIDENCE ALIGNMENT

- Prefer Document Evidence over Original Answer when correcting inconsistencies
- If evidence is weak or missing → DO NOT modify facts

---

## REFINEMENT RULES

1. Improve clarity and readability
2. Use clean Markdown (bold, bullets where needed)
3. Keep tone professional and natural
4. Preserve any ⚠️ warning EXACTLY at the top
5. Do NOT repeat the question
6. Do NOT add filler text

---

## FORMAT CONTROL

- Avoid excessive bullet points
- Keep answer smooth and readable
- Do NOT over-format

---

## OUTPUT

Return ONLY the final improved answer.
`;

    const improved = await callGeminiWithTimeout(prompt);

    // safety fallback
    if (!improved || improved.trim().length < 10) {
      return ragAnswer;
    }

    return improved.trim();

  } catch (error) {

    logger.warn("[GeminiReasoning] skipped:", error.message);

    // fallback to original answer
    return ragAnswer;

  }

}


module.exports = {
  applyReasoning
};